CUDA_VISIBLE_DEVICES=1 python ./downstream/faith_thr.py \
-d ioi \
-c resid_post \
-n 1024 \
-mt attrib \
--model pythia-160m \
-w faithfulness \
--sae_folder_path /home/fbelotti/group-sae/saes/pythia_160-topk \
--effects_dir /home/fbelotti/group-sae/effects_pass_through \
--task_dir /home/fbelotti/group-sae/downstream/tasks \
--faith_dir /home/fbelotti/group-sae/faithfulness_pass_through_thr \
--n_devices 1
