CUDA_VISIBLE_DEVICES=1 python downstream/effects.py \
-d ioi \
-c resid_post \
-n 1024 \
-l 15 \
-m pythia-160m \
-mt attrib \
--sae_folder_path /home/fbelotti/group-sae/saes/pythia_160-topk \
--device cuda \
--effects_dir /home/fbelotti/group-sae/effects_pass_through \
--task_dir /home/fbelotti/group-sae/downstream/tasks \
--batch_size 16 \
--n_devices 1
