python ../downstream/faith.py \
-d ioi \
-c resid_post \
-n 1024 \
-mt attrib \
--model pythia-160m-deduped \
-w faithfulness \
--sae_folder_path /home/fbelotti/group-sae/training/checkpoints/EleutherAI/pythia-160m-deduped-1024-jr-lambda-0.5-target-L0-128-lr-0.0007/step_139998 \
--effects_dir /home/fbelotti/group-sae/downstream/effects \
--task_dir /home/fbelotti/group-sae/downstream/tasks \
--n_devices 2
